services:
  - type: web
    name: edusphere
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python app.py init_db
      python app.py seed_db
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
    disk:
      name: edusphere-data
      mountPath: /opt/render/project/src/instance
      sizeGB: 1